services:
    pgvector:
        image: 'pgvector/pgvector:pg16'
        environment:
            - POSTGRES_PASSWORD=password
        restart: unless-stopped
        ports:
            - '5432:5432'
        container_name: pgvector

